/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthenticatedVehiclesRouteImport } from "./routes/_authenticated/vehicles"
import { Route as AuthenticatedRoutesRouteImport } from "./routes/_authenticated/routes"
import { Route as AuthenticatedDriversRouteImport } from "./routes/_authenticated/drivers"
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated/dashboard"
import { Route as AuthenticatedRoutesRouteIdRouteImport } from "./routes/_authenticated/routes_.$routeId"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: "/vehicles",
  path: "/vehicles",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: "/routes",
  path: "/routes",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: "/drivers",
  path: "/drivers",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutesRouteIdRoute =
  AuthenticatedRoutesRouteIdRouteImport.update({
    id: "/routes_/$routeId",
    path: "/routes/$routeId",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/dashboard": typeof AuthenticatedDashboardRoute
  "/drivers": typeof AuthenticatedDriversRoute
  "/routes": typeof AuthenticatedRoutesRoute
  "/vehicles": typeof AuthenticatedVehiclesRoute
  "/routes/$routeId": typeof AuthenticatedRoutesRouteIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/dashboard": typeof AuthenticatedDashboardRoute
  "/drivers": typeof AuthenticatedDriversRoute
  "/routes": typeof AuthenticatedRoutesRoute
  "/vehicles": typeof AuthenticatedVehiclesRoute
  "/routes/$routeId": typeof AuthenticatedRoutesRouteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/login": typeof LoginRoute
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRoute
  "/_authenticated/drivers": typeof AuthenticatedDriversRoute
  "/_authenticated/routes": typeof AuthenticatedRoutesRoute
  "/_authenticated/vehicles": typeof AuthenticatedVehiclesRoute
  "/_authenticated/routes_/$routeId": typeof AuthenticatedRoutesRouteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/dashboard"
    | "/drivers"
    | "/routes"
    | "/vehicles"
    | "/routes/$routeId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/dashboard"
    | "/drivers"
    | "/routes"
    | "/vehicles"
    | "/routes/$routeId"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/dashboard"
    | "/_authenticated/drivers"
    | "/_authenticated/routes"
    | "/_authenticated/vehicles"
    | "/_authenticated/routes_/$routeId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/vehicles": {
      id: "/_authenticated/vehicles"
      path: "/vehicles"
      fullPath: "/vehicles"
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/routes": {
      id: "/_authenticated/routes"
      path: "/routes"
      fullPath: "/routes"
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/drivers": {
      id: "/_authenticated/drivers"
      path: "/drivers"
      fullPath: "/drivers"
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/routes_/$routeId": {
      id: "/_authenticated/routes_/$routeId"
      path: "/routes/$routeId"
      fullPath: "/routes/$routeId"
      preLoaderRoute: typeof AuthenticatedRoutesRouteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedRoutesRouteIdRoute: typeof AuthenticatedRoutesRouteIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedRoutesRouteIdRoute: AuthenticatedRoutesRouteIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
